trigger:
  batch: true
  branches:
    include:
    - dev
  paths:
    include:
      - force-app/*
      - manifest/*
stages:        
  - stage: DEV
    jobs:
    - deployment: 'deployDev'
      displayName: 'Deploy em dev'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
      pool:
        vmImage: 'ubuntu-latest'

      container:
        image: salesforce/salesforcedx:latest-full
      
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                displayName: 'Checkout files at $(Build.SourceBranch)'
              - script: |
                  destdir=./auth.txt
                  cat <<< "$(sfdxUrlDev)" > "$destdir"

                  echo "sfdx auth:sfdxurl:store --sfdxurlfile $destdir --setalias $(Build.SourceBranch) --json"
                  cmd=$(sfdx auth:sfdxurl:store --sfdxurlfile $destdir --setalias $(Build.SourceBranch) --json)

                  exit_code=$(jq -r '.status' <<< "$cmd")

                  if [[ $exit_code -gt 0 ]]; then
                    echo "Erro ao autenticar com sandbox."
                    exit 1
                  else
                    echo "Autenticação realizada com sucesso."

                    echo "force:config:set defaultusername=$(Build.SourceBranch)"
                    sfdx force:config:set defaultusername=$(Build.SourceBranch)
                    exit 0
                  fi
                displayName: 'Autenticação'
              - script: |
                  echo "sfdx force:source:convert --manifest './manifest/package.xml' --outputdir ./src --json"

                  # Convert source code to metadata format
                  cmd=$(sfdx force:source:convert --manifest './manifest/package.xml' --outputdir ./src --json)

                  exit_code=$(jq -r '.status' <<< "$cmd")

                  if [[ $exit_code -gt 0 ]]; then
                    echo "Erro ao converter os metadados."
                    
                    message=$(jq -r '.message' <<< "$cmd")
                    echo $message
                    exit 1
                  else
                    echo "Conversão de metadados bem-sucedida."
                    exit 0
                  fi
                displayName: 'Converter metadados'
              - script: |
                  cmd=$(sfdx force:mdapi:deploy -l NoTestRun --deploydir ./src --targetusername $(Build.SourceBranch) --wait 60 --json) 

                  exit_code=$(jq -r '.status' <<< "$cmd")

                  if [[ $exit_code -gt 0 ]]; then
                    echo "Erro ao realizar deploy."

                    message=$(jq -r '.message' <<< "$cmd")
                    echo $message
                    exit 1
                  else
                    echo "Deploy executado com sucesso."

                    jobid=$(jq -r '.result.id' <<< "$cmd")
                    echo "##vso[task.setvariable variable=JobId]${jobid}"

                    exit 0
                  fi
                displayName: 'Deploy org'