# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo SCRATCH ORG
  displayName: 'Criar Scratch Org'

- script: echo TEST
  displayName: 'Testes do apex'

- script: echo DEPLOY DEV
  displayName: 'Deploy em dev'

- script: echo DEPLOY HOMOLOG
  displayName: 'Deploy em homolog'