trigger:
  batch: true
  branches:
    include:
    - azure-pipelines
  paths:
    include:
      - force-app/*
      - manifest/*
stages:        
  - stage: TESTE
    jobs:
    - deployment: 'deployToProduction'
      displayName: 'teste Alexandre'
      # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      pool:
        vmImage: 'ubuntu-latest'

      container:
        image: salesforce/salesforcedx:latest-full
        # endpoint: 'ACR Salesforce'
      
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                displayName: 'Checkout files at $(Build.SourceBranch)'
              - script: |
                  destdir=./auth.txt
                #  cat <<< "$(sfdxUrlProd)" > "$destdir"
                cat <<< "$(sfdxUrlProd)" > "$destdir"

                  echo "sfdx auth:sfdxurl:store --sfdxurlfile $destdir --setalias $(Build.SourceBranch) --json"
                  cmd=$(sfdx auth:sfdxurl:store --sfdxurlfile $destdir --setalias $(Build.SourceBranch) --json)

                  exit_code=$(jq -r '.status' <<< "$cmd")

                  if [[ $exit_code -gt 0 ]]; then
                    echo "Falha na autenticação com ambiente."
                    exit 1
                  else
                    echo "Autenticação realizada com sucesso."

                    echo "force:config:set defaultusername=$(Build.SourceBranch)"
                    sfdx force:config:set defaultusername=$(Build.SourceBranch)
                    exit 0
                  fi
                displayName: 'Autorizando ambiente Salesforce'